// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpHeadersSerialized, HttpSchema, HttpSearchParamsSerialized } from 'zimic/http';

export type BlinkSchema = HttpSchema<{
  '/users': {
    /** Criar usuário */
    POST: BlinkOperations['users/create'];
  };
  '/users/me': {
    /** Buscar usuário autenticado */
    GET: BlinkOperations['users/get/me'];
  };
  '/users/:userId': {
    /** Buscar usuário */
    GET: BlinkOperations['users/get'];
    /** Remover usuário */
    DELETE: BlinkOperations['users/delete'];
    /** Atualizar usuário */
    PATCH: BlinkOperations['users/update'];
  };
  '/auth/login': {
    /** Login */
    POST: BlinkOperations['auth/login'];
  };
  '/auth/logout': {
    /** Logout */
    POST: BlinkOperations['auth/logout'];
  };
  '/auth/refresh': {
    /** Gerar novo token de acesso */
    POST: BlinkOperations['auth/refresh'];
  };
  '/auth/password': {
    /** Alterar senha */
    PUT: BlinkOperations['auth/password/update'];
  };
  '/workspaces': {
    /** Listar workspaces */
    GET: BlinkOperations['workspaces/list'];
    /** Criar workspace */
    POST: BlinkOperations['workspaces/create'];
  };
  '/workspaces/:workspaceId': {
    /** Buscar workspace */
    GET: BlinkOperations['workspaces/get'];
    /** Remover workspace */
    DELETE: BlinkOperations['workspaces/delete'];
    /** Atualizar workspace */
    PATCH: BlinkOperations['workspaces/update'];
  };
  '/workspaces/:workspaceId/members': {
    /** Listar membros */
    GET: BlinkOperations['workspaces/members/list'];
    /** Adicionar membro */
    POST: BlinkOperations['workspaces/members/create'];
  };
  '/workspaces/:workspaceId/members/:memberId': {
    /** Buscar membro */
    GET: BlinkOperations['workspaces/members/get'];
    /** Atualizar membro */
    PUT: BlinkOperations['workspaces/members/update'];
    /** Remover membro */
    DELETE: BlinkOperations['workspaces/members/delete'];
  };
  '/workspaces/:workspaceId/blinks': {
    /** Listar blinks */
    GET: BlinkOperations['workspaces/blinks/list'];
    /** Criar blink */
    POST: BlinkOperations['workspaces/blinks/create'];
  };
  '/workspaces/:workspaceId/blinks/:blinkId': {
    /** Buscar blink */
    GET: BlinkOperations['workspaces/blinks/get'];
    /** Remover blink */
    DELETE: BlinkOperations['workspaces/blinks/delete'];
    /** Atualizar blink */
    PATCH: BlinkOperations['workspaces/blinks/update'];
  };
  '/:redirectId': {
    /** Redirecionar */
    GET: BlinkOperations['redirect'];
  };
}>;

export interface BlinkComponents {
  schemas: {
    User: {
      /** O id do usuário */
      id: string;
      /** O nome do usuário */
      name: string;
      /**
       * Format: email
       *
       * O email do usuário
       */
      email: string;
      /**
       * Format: date-time
       *
       * A data de criação do usuário
       */
      createdAt: string;
      /**
       * Format: date-time
       *
       * A data de atualização do usuário
       */
      updatedAt: string;
    };
    Workspace: {
      /** O id do workspace */
      id: string;
      /** O nome do workspace */
      name: string;
      /**
       * Format: date-time
       *
       * A data de criação do workspace
       */
      createdAt: string;
      /**
       * Format: date-time
       *
       * A data de atualização do workspace
       */
      updatedAt: string;
    };
    WorkspaceMember: {
      /** O id do membro */
      id: string;
      user: BlinkComponents['schemas']['User'];
      type: BlinkComponents['schemas']['WorkspaceMemberType'];
      /**
       * Format: date-time
       *
       * A data de criação do membro
       */
      createdAt: string;
      /**
       * Format: date-time
       *
       * A data de atualização do membro
       */
      updatedAt: string;
    };
    /**
     * O tipo do membro
     *
     * @enum {string}
     */
    WorkspaceMemberType: 'ADMINISTRATOR' | 'DEFAULT';
    Blink: {
      /** O id do blink */
      id: string;
      /** O nome do blink */
      name?: string | null;
      /** A url do blink */
      url: string;
      /** O id do redirecionamento */
      redirectId: string;
      /** O id do workspace */
      workspaceId: string;
      creator?: BlinkComponents['schemas']['User'];
      /**
       * Format: date-time
       *
       * A data de criação do blink
       */
      createdAt: string;
      /**
       * Format: date-time
       *
       * A data de atualização do blink
       */
      updatedAt: string;
    };
    ValidationError: {
      /** A mensagem de erro */
      message: string;
      /** Os problemas de validação */
      issues?: ({
        /** A mensagem de erro */
        message?: string;
        /** O código do erro */
        code?: string;
        /** O caminho do erro */
        path?: (string | number)[];
      } & {
        [key: string]: any;
      })[];
      /** O código do erro */
      code?: string;
    };
    AuthError: {
      /** A mensagem de erro */
      message: string;
      /** O código do erro */
      code?: string;
    };
    NotFoundError: {
      /** A mensagem de erro */
      message: string;
      /** O código do erro */
      code?: string;
    };
    ConflictError: {
      /** A mensagem de erro */
      message: string;
      /** O código do erro */
      code?: string;
    };
    InternalServerError: {
      /** A mensagem de erro */
      message: string;
      /** O código do erro */
      code?: string;
    };
  };
}

export interface BlinkOperations {
  'users/create': HttpSchema.Method<{
    request: {
      body: {
        /** O nome do usuário */
        name: string;
        /**
         * Format: email
         *
         * O email do usuário
         */
        email: string;
        /** A senha do usuário */
        password: string;
      };
    };
    response: {
      /** Usuário criado */
      201: {
        body: BlinkComponents['schemas']['User'];
      };
      /** Erro de validação */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Email em uso por outro usuário */
      409: {
        body: BlinkComponents['schemas']['ConflictError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'users/get/me': HttpSchema.Method<{
    response: {
      /** Usuário encontrado */
      200: {
        body: BlinkComponents['schemas']['User'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Usuário não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'users/get': HttpSchema.Method<{
    response: {
      /** Usuário encontrado */
      200: {
        body: BlinkComponents['schemas']['User'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Usuário não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'users/delete': HttpSchema.Method<{
    response: {
      /** Usuário removido */
      204: {};
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Usuário não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'users/update': HttpSchema.Method<{
    request: {
      body: {
        /** O nome do usuário */
        name?: string;
        /**
         * Format: email
         *
         * O email do usuário
         */
        email?: string;
      };
    };
    response: {
      /** Usuário atualizado */
      200: {
        body: BlinkComponents['schemas']['User'];
      };
      /** Erro de validação */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Usuário não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Email em uso por outro usuário */
      409: {
        body: BlinkComponents['schemas']['ConflictError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'auth/login': HttpSchema.Method<{
    request: {
      body: {
        /**
         * Format: email
         *
         * O email do usuário
         */
        email: string;
        /** A senha do usuário */
        password: string;
      };
    };
    response: {
      /** Usuário autenticado */
      204: {};
      /** Erro de validação */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Credenciais inválidas */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'auth/logout': HttpSchema.Method<{
    response: {
      /** Usuário deslogado */
      204: {};
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'auth/refresh': HttpSchema.Method<{
    response: {
      /** Novo token de acesso gerado */
      204: {};
      /** Erro de validação */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Credenciais inválidas */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'auth/password/update': HttpSchema.Method<{
    request: {
      body: {
        /** A senha atual */
        oldPassword: string;
        /** A nova senha */
        newPassword: string;
      };
    };
    response: {
      /** Senha alterada */
      204: {};
      /** Erro de validação ou senha atual inválida */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/list': HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        /** O nome do workspace para filtrar */
        name?: string;
        /** O número da página */
        page?: number;
        /** O número de workspaces por página */
        limit?: number;
      }>;
    };
    response: {
      /** Workspaces listados */
      200: {
        body: {
          workspaces: BlinkComponents['schemas']['Workspace'][];
          /**
           * @example
           *   1;
           */
          total: number;
        };
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/create': HttpSchema.Method<{
    request: {
      body: {
        /** O nome do workspace */
        name: string;
      };
    };
    response: {
      /** Workspace criado */
      201: {
        body: BlinkComponents['schemas']['Workspace'];
      };
      /** Erro de validação */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/get': HttpSchema.Method<{
    response: {
      /** Workspace encontrado */
      200: {
        body: BlinkComponents['schemas']['Workspace'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Workspace não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/delete': HttpSchema.Method<{
    response: {
      /** Workspace removido */
      204: {};
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Workspace não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/update': HttpSchema.Method<{
    request: {
      body: {
        /** O nome do workspace */
        name?: string;
      };
    };
    response: {
      /** Workspace atualizado */
      200: {
        body: BlinkComponents['schemas']['Workspace'];
      };
      /** Erro de validação */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Workspace não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/members/list': HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        /** O nome do membro para filtrar */
        name?: string;
        /** O tipo do membro para filtrar */
        type?: BlinkComponents['schemas']['WorkspaceMemberType'];
        /** O número da página */
        page?: number;
        /** O número de membros por página */
        limit?: number;
      }>;
    };
    response: {
      /** Membros listados */
      200: {
        body: {
          members: BlinkComponents['schemas']['WorkspaceMember'][];
          /**
           * @example
           *   1;
           */
          total: number;
        };
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Workspace não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/members/create': HttpSchema.Method<{
    request: {
      body: {
        userId: string;
        type?: BlinkComponents['schemas']['WorkspaceMemberType'];
      };
    };
    response: {
      /** Membro adicionado */
      201: {
        body: BlinkComponents['schemas']['WorkspaceMember'];
      };
      /** Erro de validação */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Workspace não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Usuário já é membro do workspace */
      409: {
        body: BlinkComponents['schemas']['ConflictError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/members/get': HttpSchema.Method<{
    response: {
      /** Membro encontrado */
      200: {
        body: BlinkComponents['schemas']['WorkspaceMember'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Membro não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/members/update': HttpSchema.Method<{
    request: {
      body: {
        type?: BlinkComponents['schemas']['WorkspaceMemberType'];
      };
    };
    response: {
      /** Membro atualizado */
      200: {
        body: BlinkComponents['schemas']['WorkspaceMember'];
      };
      /** Erro de validação */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Membro não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/members/delete': HttpSchema.Method<{
    response: {
      /** Membro removido */
      204: {};
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Membro não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/blinks/list': HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        /** O nome do blink para filtrar */
        name?: string;
        /** O número da página */
        page?: number;
        /** O número de blinks por página */
        limit?: number;
      }>;
    };
    response: {
      /** Blinks listados */
      200: {
        body: {
          blinks: BlinkComponents['schemas']['Blink'][];
          /**
           * @example
           *   1;
           */
          total: number;
        };
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Workspace não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/blinks/create': HttpSchema.Method<{
    request: {
      body: {
        /** O nome do blink */
        name?: string;
        /** A url do blink */
        url: string;
        /** O id do redirecionamento (se não fornecido, será gerado automaticamente) */
        redirectId?: string;
      };
    };
    response: {
      /** Blink criado */
      201: {
        body: BlinkComponents['schemas']['Blink'];
      };
      /** Erro de validação */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Workspace não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Id de redirecionamento em uso por outro blink */
      409: {
        body: BlinkComponents['schemas']['ConflictError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/blinks/get': HttpSchema.Method<{
    response: {
      /** Blink encontrado */
      200: {
        body: BlinkComponents['schemas']['Blink'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Workspace ou blink não encontrados */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/blinks/delete': HttpSchema.Method<{
    response: {
      /** Blink removido */
      204: {};
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Blink não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  'workspaces/blinks/update': HttpSchema.Method<{
    request: {
      body: {
        /** O nome do blink */
        name?: string;
        /** A url do blink */
        url?: string;
        /** O id do redirecionamento */
        redirectId?: string;
      };
    };
    response: {
      /** Blink atualizado */
      200: {
        body: BlinkComponents['schemas']['Blink'];
      };
      /** Erro de validação */
      400: {
        body: BlinkComponents['schemas']['ValidationError'];
      };
      /** Não autenticado */
      401: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Não autorizado */
      403: {
        body: BlinkComponents['schemas']['AuthError'];
      };
      /** Blink não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Id de redirecionamento em uso por outro blink */
      409: {
        body: BlinkComponents['schemas']['ConflictError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
  redirect: HttpSchema.Method<{
    response: {
      /** Redirecionamento */
      308: {
        headers: HttpHeadersSerialized<{
          location?: string;
          'cache-control'?: string;
        }>;
      };
      /** Redirecionamento não encontrado */
      404: {
        body: BlinkComponents['schemas']['NotFoundError'];
      };
      /** Erro no servidor */
      500: {
        body: BlinkComponents['schemas']['InternalServerError'];
      };
    };
  }>;
}
